background:     #171414
foreground:     #f7f3f2

color0:         #3c3838
color8:         #565151

color1:         #fa4d56
color9:         #fa4d56

color2:         #42be65
color10:        #42be65

color3:         #fddc69
color11:        #fddc69

color4:         #4589ff
color12:        #4589ff

color5:         #ff7eb6
color13:        #ff7eb6

color6:         #3ddbd9
color14:        #3ddbd9

color7:         #e5e0df
color15:        #cac5c4
